# Site settings
title: >
 Where to take my talents to - a world happiness analysis
description: >
 In the summer of 2010, in a much anticipated decision,
 NBA all-star Lebron James announced to the world that
 he would be taking his talents to South Beach to join
 the Miami Heat. This makes us question - is Miami, Florida
 really the best place for one to take their talents to?
 In this report, we analyze the World Happiness Report
 dataset to determine the top destinations around the
 world in terms of overall happiness. The happiness scores
 utilize data from the Gallup World Poll which collects
 answers in a Candril ladder survey format. Respondents
 are asked to think of a ladder with the best possible
 life for them being a 10, and the worst being a 0 and
 to rate their current lives on such scale. The dataset
 consists of over 150 countries from the years 2015 to
 2020, consisting of features such as life expectancy,
 economic product, corruption and much more. While our
 travel decisions may not be as complicated as Lebron
 James’, we hope to analyze the dataset to effectively
 assess the past, current and future well-being of
 nations around the world.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://locahost:4000" # the base hostname & protocol for your site
github_username:  ada-data-story

# Build settings
markdown: kramdown
